version: '3'
services:
  download:
    build: .
    command: bash -c "cd /app/ && scrapy runspider pdf_downloader.py"

  download_humblebundle:
    build: .
    command: bash -c "cd /app/ && scrapy runspider download_humblebundle.py"
    environment:
      - KEY=6AS5HeVNvSsnPKSf